### ISSUE TITLE
installation done with docker option and bookkeeper errored Permission denied

### ISSUE THREAD

**Issue by kuldeep-apte** [mercure-imaging/mercure#38]
2022-07-25 06:17:09,678 CRITICAL __init__: Traceback (most recent call last):
  File "/opt/mercure/app/bookkeeper.py", line 32, in <module>
    from bookkeeping.database import *
  File "/opt/mercure/app/bookkeeping/database.py", line 16, in <module>
    import bookkeeping.config as bk_config
  File "/opt/mercure/app/bookkeeping/config.py", line 20, in <module>
    bookkeeper_config = Config((os.getenv("MERCURE_CONFIG_FOLDER") or "/opt/mercure/config") + "/bookkeeper.env")
  File "/opt/mercure/env/lib/python3.8/site-packages/starlette/config.py", line 61, in __init__
    self.file_values = self._read_file(env_file)
  File "/opt/mercure/env/lib/python3.8/site-packages/starlette/config.py", line 116, in _read_file
    with open(file_name) as input_file:
PermissionError: [Errno 13] Permission denied: '/opt/mercure/config/bookkeeper.env'

**Comment by tblock79** [comment]
Sounds like a problem related to incorrect file permissions of this particular server installation. The Docker-type installation in a clean VM via Vagrant works and does not produce this error. Please provide more specific information on the installation to the support forum.

Closing this issue as it does not appear to be a general problem.
